FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
COPY /bin/Release/netcoreapp3.0/ app/
COPY /wwwroot/ app/wwwroot/
RUN apt-get update
RUN apt-get install -y python3 
RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl
RUN ln -s /usr/bin/python3 /usr/local/bin/python
EXPOSE 80 443 5000 5001
WORKDIR app
ENTRYPOINT ["dotnet", "KittenSignalR.dll"]